services:
  # RxInferServer - Julia API server for RxInfer
  rxinfer-server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - RXINFER_SERVER_PORT=8000
      - RXINFER_SERVER_DEV_TOKEN=dev-token
    depends_on:
      - otel-collector

  # Swagger UI for viewing OpenAPI specifications
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi:/openapi
    environment:
      SWAGGER_JSON: "/openapi/spec.yaml"

  # OpenTelemetry Collector for metrics, traces, and logs
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
    volumes:
      - ./telemetry/otel-collector.yaml:/etc/otel-collector.yaml
    command: ["--config=/etc/otel-collector.yaml"]
    
  # Prometheus for metrics collection and visualization
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"   # Prometheus web UI
    volumes:
      - ./telemetry/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - otel-collector
      
  # Loki for log aggregation
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
      
  # Tempo for distributed tracing
  tempo:
    image: grafana/tempo:latest
    ports:
      - "14268" # jaeger ingest
      - "3200"  # tempo UI
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"  # zipkin
    command: [ "-config.file=/etc/tempo/tempo-config.yaml" ]
    volumes:
      - ./telemetry/tempo-config.yaml:/etc/tempo/tempo-config.yaml
      
  # Grafana for visualization of metrics and logs
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    volumes:
      - ./telemetry/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus
      - loki
      - tempo